version: "3.8"

services:
  db:
    container_name: portfolio_db
    image: postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - default
    restart: unless-stopped

  api:
    depends_on:
      - db
    build:
      dockerfile: /compose/api/Dockerfile
    container_name: api
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_PASSWORD=test
      - DB_USER=test
      - DB_NAME=test
    ports:
      - "8000:8000"
    networks:
      - default


networks:
  default:
    driver: bridge

volumes:
  db:

