version: "3.8"

services:
  db:
    container_name: portfolio_db
    image: postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - default
    restart: unless-stopped


networks:
  default:
    driver: bridge

volumes:
  db:

